### ISSUE TITLE
New Feature - Not fail Jenkins build when test cases fail

### ISSUE THREAD

**Issue by kycan** [deliverymind/lightning#60]
Can we have a option to not fail the a Jenkins build or set the build to unstable status when a test case fails?

Have an option to have the return code always be 0?

**Comment by automatictester** [comment]
You can override status code returned by Lightning as explained here:
http://stackoverflow.com/questions/14392349/dont-fail-jenkins-build-if-execute-shell-fails
This way you can make it always be 0.

If you want to set the build to unstable rather than failed, this is something you need to configure in your Jenkins job, rather than in Lightning:
http://stackoverflow.com/questions/25442343/failure-unstable-via-script-return-code

Does it solve your problem?

**Comment by kycan** [comment]
Yes, it does.

Thank you.
