### ISSUE TITLE
Ability to set UNSTABLE for Jenkins builds

### ISSUE THREAD

**Issue by ravitej-aluru** [deliverymind/lightning#68]
It would be really very useful to have the ability to also set Jenkins builds to UNSTABLE in addition to the FAILED status already provided. For example, the below test allows to set the build to FAILED if avg. response time is greater than 4000. It would be really useful to add ability to set the build to UNSTABLE if avg. response time is between 3000 and 4000.
```
<avgRespTimeTest>
    <testName>Test #1</testName>
    <description>Verify average login times</description>
    <transactionName>Login</transactionName>
    <regexp/>
    <maxAvgRespTime>4000</maxAvgRespTime>
    **<unstableAvgRespTime>3000</unstableAvgRespTime>**
</avgRespTimeTest>
```

**Comment by automatictester** [comment]
Thanks for sharing your thoughts and providing some recommendations.
I have a fundamental problem with Jenkins reporting build status as either unstable or failed, depending on what went wrong. I believe in simplicity - if it doesn't work, it doesn't work. As simple as that. There is lots of people in the IT community who find Jenkins' unstable vs failed thing utmostly confusing.

Let's assume for a while that we want to go ahead and implement what you suggested
- As unstable vs failed is a Jenkins-only concept, this would have to be a CI server-specific functionality. 
- We need a logic to handle unstable result reported by one test and failed reported by another, as part of the same run.

It is a bit of work, for functionality that is in my eyes at most a nice-to-have. I'm happy to discuss further the problem you are trying to solve. I have a feeling we are trying to solutionise too early, without understanding what the actual problem is.

If you want to provide a pull request, I'm happy to comment on that too, but cannot guarentee this will get merged.

**Comment by ravitej-aluru** [comment]
Sorry for the delay. I understand where you are coming from. It is indeed a Jenkins only concept. However, I find that being able to set a build status to unstable in addition to pass and fail useful. It may not be necessary for every job/project, but in some cases it is very useful.

Using my example above, the requirement for my app is that if certain request's response time is over 4000 ms, it is definitely a failure. But if it is between 3000 ms and 4000 ms, the app may be released depending on further tests in the following pipeline. This is just one use case.

I completely understand your argument thought about it being a CI server specific functionality for your app to handle. I'll see if I can work on implementing and create a PR when I do.

Appreciate your reply and your app in the first place.
